[2017-11-03 18:08:02]---错误信息发送数据{"serverCode": 1} 读取http://121.41.30.108/site/v1.0/getDTUProjectByServerCode接口出错HTTPConnectionPool(host='121.41.30.108', port=80): Max retries exceeded with url: /site/v1.0/getDTUProjectByServerCode (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000000D58E978>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))!
[2017-11-03 18:08:02]---'NoneType' object has no attribute 'get'
[2017-11-03 18:08:04]---错误信息发送数据{"timeZone": "afda", "serverCode": 1000, "RTBName": "rJIefdMZ", "dtuName": "newtest001"} 读取http://121.41.30.108/site/v1.0/updateDTUProjectByName接口出错HTTPConnectionPool(host='121.41.30.108', port=80): Max retries exceeded with url: /site/v1.0/updateDTUProjectByName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000000E4223C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))!
[2017-11-03 18:08:04]---'NoneType' object has no attribute 'get'
